# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'This project aim to deal with modules related to the management
    of warehouses. You''ll find modules that:'
repo_name: Odoo Stock Logistics Warehouse
repo_slug: stock-logistics-warehouse
repo_website: https://github.com/OCA/stock-logistics-warehouse
travis_apt_packages: []
travis_apt_sources: []

