# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.4
_src_path: gh:oca/oca-addons-repo-template
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: "TODO: add repo description."
repo_name: stock-logistics-warehouse
repo_slug: stock-logistics-warehouse
travis_apt_packages: []
travis_apt_sources: []
