{
    "name": "Sale Stock On Hand Popup",
    "author": "PyTech SRL, Ooops404, Odoo Community Association (OCA)",
    "maintainers": ["aleuffre", "renda-dev", "PicchiSeba"],
    "website": "https://github.com/OCA/stock-logistics-warehouse",
    "category": "Warehouse Management",
    "version": "14.0.1.0.1",
    "license": "AGPL-3",
    "depends": ["sale_stock", "stock_available"],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "views/assets.xml",
        "views/res_config_settings_views.xml",
        "views/sale_order_views.xml",
        "wizards/product_quant_wizard_views.xml",
    ],
    "qweb": ["static/src/xml/stock_on_hand_widget.xml"],
    "installable": True,
    "application": False,
}
