{'name': 'Stock Reserve Sales',
 'version': '12.0.1.0.0',
 'author': "Camptocamp,Odoo Community Association (OCA)",
 'category': 'Warehouse',
 'license': 'AGPL-3',
 'complexity': 'normal',
 'website': "https://github.com/OCA/stock-logistics-warehouse",
 'depends': ['sale_stock',
             'stock_reserve'
             ],
 'demo': [],
 'data': ['security/ir.model.access.csv',
          'wizard/sale_stock_reserve_view.xml',
          'views/sale.xml',
          'views/stock_reserve.xml',
          ],
 'test': ['test/sale_reserve.yml',
          'test/sale_line_reserve.yml',
          ],
 'installable': True,
 'auto_install': False,
 }
