from . import stock_move
from . import stock_picking
from . import stock_location
from . import stock_quant
from . import stock_inventory
from . import stock_quant_package
from . import product_template
from . import product_product
from . import res_users
from . import stock_warehouse
from . import stock_move_line
