{'name': 'Stock Reservation',
 'summary': 'Stock reservations on products',
 'version': '12.0.1.0.0',
 'author': "Camptocamp,Odoo Community Association (OCA)",
 'category': 'Warehouse',
 'license': 'AGPL-3',
 'complexity': 'normal',
 'website': "https://github.com/OCA/stock-logistics-warehouse",
 'depends': ['stock',
             ],
 'data': ['views/stock_reserve.xml',
          'views/product.xml',
          'data/stock_data.xml',
          'security/ir.model.access.csv',
          ],
 'auto_install': False,
 'test': ['tests/stock_reserve.yml',
          ],
 'installable': True,
 }
