[project]
name = "odoo-addons-oca-stock-logistics-warehouse"
version = "19.0.20260225.0"
dependencies = [
    "odoo-addon-stock_inventory==19.0.*",
    "odoo-addon-stock_inventory_lockdown==19.0.*",
    "odoo-addon-stock_inventory_lockdown_product==19.0.*",
    "odoo-addon-stock_warehouse_calendar==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
